#! /usr/bin/env python

import click

@click.group()
def cli():
  """ config tool for docker-compose projects"""
  pass

@cli.command()
@click.option('--https', default=False, type=bool)
@click.option('--template', '-t', default="proxy", type=str)
@click.option('--port', '-p', default=-1, type=int)
@click.option('--server', '-s', default="localhost", multiple=True)
@click.option('--echo', default=False, type=bool)
@click.option('--sslcrt', default="", type=str)
@click.option('--sslkey', default="", type=str)
@click.option('--output', default="", type=str)
@click.option('--webroot', default="", type=str)
def nginx(https, template, port, server, echo, sslcrt, sslkey, output, webroot):

  if template == 'static' and webroot == "":
    click.echo("webroot should be provided")
    exit()

  if https:
    template += '_https'
    if port < 0:
      port = 443
  else:
    template += '_http'
    if port < 0:
      port = 80

  template_dir = './templates'
  template_path = "%s/%s.conf" % (template_dir, template)

  try:
    fd = open(template_path)
    conf = fd.read()
    fd.close()
  except:
    click.echo("no such template")
    exit()

  if template.startswith("proxy"):
    conf = conf.replace("LOCAL_PORT", str(port))
  
  if template.startswith("static"):
    conf = conf.replace("WEB_ROOT", webroot)

  conf = conf.replace("SERVER1", " ".join(server))
  conf = conf.replace("SERVER2", server[0])

  if https:
    conf = conf.replace("SSL_CRT", sslcrt)
    conf = conf.replace("SSL_KEY", sslkey)

  if echo:
    click.echo(conf)

  if output != "":
    fd = open(output, "w")
    fd.write(conf)
    fd.close()

@cli.command()
def env():
  click.echo('Initialized the database')

if __name__ == '__main__':
  cli()
